# Generated by Django 5.1.2 on 2024-10-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "question_severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Basic"),
                            ("2", "Medium"),
                            ("3", "High"),
                            ("4", "Advanced"),
                            ("5", "Highest"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("question_preamble", models.TextField(blank=True, null=True)),
                ("question_main", models.TextField(blank=True, null=True)),
                ("a", models.CharField(blank=True, max_length=255, null=True)),
                ("b", models.CharField(max_length=255)),
                ("c", models.CharField(max_length=255)),
                ("d", models.CharField(max_length=255)),
                ("e", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
